In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
from torch.autograd import Variable, Function

In [20]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x**2 + y**2
f = x + y + z
s1 = 6 * f.sum()
s2 = f.sum()

In [21]:
s1.backward(retain_graph=True)

In [5]:
x.grad

tensor([18., 30., 42.])

In [6]:
s2.backward()

In [7]:
x.grad

tensor([21., 35., 49.])

In [8]:
class GRL(Function):
    @staticmethod
    def forward(self, i):
        return i

    @staticmethod
    def backward(self, grad_output):
        grad_output = grad_output.neg()
        return grad_output

In [9]:
s3 = (x-y).sum()

In [10]:
s3 = GRL.apply(s3)

In [11]:
s3.backward()

In [12]:
x.grad

tensor([20., 34., 48.])